[build]
builder = "NIXPACKS"
buildCommand = "cd backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/integrators-backend-1.0.0.jar"
healthcheckPath = "/api/products/services"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
